name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Git
        run: sudo apt-get install git -y  # Ensure Git is installed

      - name: Remove existing cicdhtml directory if it exists
        run: |
          if [ -d "/tmp/cicdhtml" ]; then
            rm -rf /tmp/cicdhtml
          fi

      - name: Remove existing files in /var/www/html/ if it exists
        run: |
          if [ -d "/var/www/html" ]; then
            rm -rf /var/www/html/*
          fi

      - name: Clone Repository
        run: git clone https://github.com/madhanumk/cicdhtml.git /tmp/cicdhtml

      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "/tmp/cicdhtml/*"  # Adjust source to point to the cloned directory
          target: "/var/www/html/"
          strip_components: 1        # Optional: strip leading directory from file paths
