name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa  # Set the correct permissions for the SSH private key
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts  # Add EC2 host to known_hosts

      - name: Remove existing directory /var/www/html if it exists
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "sudo rm -rf /var/www/html"

      - name: Clone Repository to EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          sudo mkdir -p /var/www/html  # Ensure the directory exists
          sudo git clone https://github.com/madhanumk/cicdhtml.git /var/www/html  # Clone the repository
          EOF

      - name: Cleanup
        run: |
          rm -rf ~/.ssh/id_rsa  # Remove the private SSH key from the runner for security
