name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Remove existing files in /var/www/html/ if it exists
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          ssh -o StrictHostKeyChecking=no -i /dev/stdin ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "sudo rm -rf /var/www/html/*"

      - name: Clone Repository to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" | ssh -i /dev/stdin ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          git clone https://github.com/madhanumk/cicdhtml.git /var/www/html
          EOF
