name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # This job runs on an Ubuntu environment

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up SSH agent and add the private key
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 3: Add the server's known host key (optional)
      - name: Add SSH host key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      # Step 4: Execute the script on the remote server
      - name: Run script on Ubuntu server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@54.158.243.223 'bash -s' < /var/www/html/auto_deploy.sh

            
