name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Remove existing files in /var/www/html/ if it exists
        run: |
          if [ -d "/var/www/html" ]; then
            sudo rm -rf /var/www/html/*
          fi

      - name: Create Tar Archive
        run: |
          tar czf cicdhtml.tar.gz .  # Create tar archive of the current directory

      - name: Copy Tar Archive to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" | ssh -o StrictHostKeyChecking=no -i /dev/stdin ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "mkdir -p /var/www/html && tar xzf - -C /var/www/html" < cicdhtml.tar.gz
