name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Remove existing files in /var/www/html/ if it exists
        run: |
          if [ -d "/var/www/html" ]; then
            sudo rm -rf /var/www/html/*
          fi

      - name: Clone Repository to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i "${{ secrets.EC2_SSH_KEY }}" ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "git clone https://github.com/madhanumk/cicdhtml.git /var/www/html"

